version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  reviewers:
  - gonace
